import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

import type { ExtractedInvoice } from "./rescue-types";

const SLATE_900: [number, number, number] = [15, 23, 42];
const SLATE_500: [number, number, number] = [100, 116, 139];
const EMERALD: [number, number, number] = [5, 150, 105];

function safeFilenamePart(text: string, max = 28): string {
  const t = text.replace(/[^\w\s-]/g, "").replace(/\s+/g, "-").slice(0, max);
  return t || "invoice";
}

/**
 * Builds a clean A4 PDF from structured invoice fields (browser-only).
 */
export function downloadInvoicePdf(invoice: ExtractedInvoice): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 18;
  let cursorY = 0;

  doc.setFillColor(...EMERALD);
  doc.rect(0, 0, pageW, 16, "F");
  doc.setDrawColor(...SLATE_900);
  doc.setLineWidth(0.2);
  doc.line(0, 16, pageW, 16);

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("Receipt Rescue", margin, 10.5);

  doc.setTextColor(...SLATE_900);
  doc.setFontSize(22);
  doc.text("Invoice", margin, 28);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...SLATE_500);
  doc.text("Structured extraction report", margin, 34);

  cursorY = 44;

  const label = (x: number, y: number, text: string) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...SLATE_500);
    doc.text(text.toUpperCase(), x, y);
  };
  const value = (x: number, y: number, text: string) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    doc.setTextColor(...SLATE_900);
    doc.text(text, x, y);
  };

  const col2 = margin + 72;
  label(margin, cursorY, "Customer");
  value(margin, cursorY + 5, invoice.customerName);
  label(col2, cursorY, "Date");
  value(col2, cursorY + 5, invoice.date);

  cursorY += 18;
  label(margin, cursorY, "Payment status");
  value(margin, cursorY + 5, invoice.paymentStatus);
  label(col2, cursorY, "AI confidence");
  value(col2, cursorY + 5, `${invoice.aiConfidence}%`);

  cursorY += 22;

  autoTable(doc, {
    startY: cursorY,
    head: [["Description", "Qty", "Unit (Rs)", "Amount (Rs)"]],
    body: invoice.items.map((row) => [
      row.name,
      String(row.quantity),
      row.price.toFixed(2),
      (row.price * row.quantity).toFixed(2),
    ]),
    foot: [["", "", "Total", `Rs ${invoice.totalAmount.toFixed(2)}`]],
    theme: "plain",
    styles: {
      fontSize: 9,
      cellPadding: { top: 2.5, bottom: 2.5, left: 3, right: 3 },
      textColor: SLATE_900,
      lineColor: [226, 232, 240],
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: SLATE_900,
      textColor: [248, 250, 252],
      fontStyle: "bold",
      halign: "left",
    },
    footStyles: {
      fillColor: [241, 245, 249],
      textColor: SLATE_900,
      fontStyle: "bold",
    },
    columnStyles: {
      0: { cellWidth: 78 },
      1: { halign: "center", cellWidth: 18 },
      2: { halign: "right", cellWidth: 32 },
      3: { halign: "right", cellWidth: 36 },
    },
    margin: { left: margin, right: margin },
    didDrawPage: (data) => {
      const footY = doc.internal.pageSize.getHeight() - 10;
      doc.setFontSize(8);
      doc.setTextColor(...SLATE_500);
      doc.setFont("helvetica", "normal");
      doc.text(
        `Generated by Receipt Rescue · ${new Date().toISOString().slice(0, 10)}`,
        margin,
        footY
      );
      doc.text(`Page ${data.pageNumber}`, pageW - margin - 12, footY, { align: "right" });
    },
  });

  const name = safeFilenamePart(invoice.customerName);
  doc.save(`receipt-rescue-invoice-${name}-${invoice.date}.pdf`);
}
